version: "3.9"

services:
  nginx:
    image: nginx:alpine
    container_name: reverse-proxy
    ports:
      - "80:80"
    volumes:
      - ./nginx/proxy.conf:/etc/nginx/conf.d/default.conf:ro
    depends_on:
      - frontend
      - backend
    restart: always

  frontend:
    build: ./frontend
    container_name: frontend
    expose:
      - "80"
    restart: always

  db:
    image: postgres:15
    container_name: postgres
    environment:
      - POSTGRES_USER=konempleo
      - POSTGRES_PASSWORD=konempleo_pw
      - POSTGRES_DB=konempleo
    volumes:
      - pgdata:/var/lib/postgresql/data
    restart: always

  backend:
    build:
      context: ..
      dockerfile: Dockerfile
    container_name: backend

    env_file:
      - ../app/.env

    environment:
      - DATABASE_URL=postgresql://konempleo:konempleo_pw@db:5432/konempleo
      - DB_HOST=db
      - DB_PORT=5432
      - DB_NAME=konempleo
      - DB_USER=konempleo
      - DB_PASSWORD=konempleo_pw

      # AWS S3 con IAM Role (sin keys)
      - AWS_REGION=us-east-2
      - AWS_S3_BUCKET=konempleo-prod-bucket
      - AWS_S3_PRESIGN_EXPIRATION=900

    depends_on:
      - db
    expose:
      - "8000"
    restart: always

volumes:
  pgdata:
