
# HTTP (80) - Challenge + Redirect
# HTTP (80) - Challenge + Redirect a HTTPS
# =========================
server {
    listen 80;
    server_name deepvoicelabs.com www.deepvoicelabs.com;
    # Certbot challenge

    # Let’s Encrypt challenge

    location /.well-known/acme-challenge/ {
        root /var/www/certbot;
    }

    # Todo lo demás -> HTTPS
    location / {
        return 301 https://$host$request_uri;
    }
}

# =========================
# HTTPS (443) - Producción
# =========================
server {
    listen 443 ssl;
    server_name deepvoicelabs.com www.deepvoicelabs.com;

    ssl_certificate     /etc/letsencrypt/live/deepvoicelabs.com/fullchain.pem;
    ssl_certificate_key /etc/letsencrypt/live/deepvoicelabs.com/privkey.pem;


    # FRONTEND Nuxt (estático)

    # FRONTEND estático

    location / {
        root /usr/share/nginx/html;
        try_files $uri $uri/ /index.html;
    }

    # BACKEND (ej: API)
    location /api/ {
        proxy_pass http://backend:8000/;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $scheme;
    }
}

